# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GgeumYeonGgeumJu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GgeumYeonGgeumJu

  pod 'RxSwift', '~> 5.1.1'
  pod 'RxCocoa', '~> 5.1.1'
  pod 'Kingfisher', '~> 5.13.0'
  pod 'SnapKit', '~> 5.0.1'
  pod 'Macaw', '0.9.6'
  pod 'Charts'
  pod 'Alamofire', '~> 5.1'

end
